### PR TITLE
QiskitDevice.probabilities() changed to QiskitDevice.probability() to…

### PR DESCRIPTION
**Pull request by rafaelha**
… restore compatibility with pennylane python package

### CODE REVIEW

**Comment by antalszava** [comment]
Hi @rafaelha, thank you so much for your pull request! :confetti_ball: 

Adjusting the name of the `QiskitDevice.probabilities` method is a change that is upcoming in this plugin as we are porting to the use of `QubitDevice` from PennyLane.

I'd be curious, was there perhaps a bug or any problems that you have faced while using `QiskitDevice.probabilities`?

**Comment by rafaelha** [comment]
> Hi @rafaelha, thank you so much for your pull request! 🎊
> 
> Adjusting the name of the `QiskitDevice.probabilities` method is a change that is upcoming in this plugin as we are porting to the use of `QubitDevice` from PennyLane.
> 
> I'd be curious, was there perhaps a bug or any problems that you have faced while using `QiskitDevice.probabilities`?

Hi, yes, running a qnode on a qiskit device that returns `qml.probs` raises `NotImplementedError: Returning probability not currently supported by qiskit.ibmq`. This seems to be because pennylane  calls the function `Device.probability` (https://github.com/XanaduAI/pennylane/blob/a776dbecfb0c1d32bb04012a69ee0e559d58c3b5/pennylane/_device.py) instead of `QiskitDevice.probabilities`. Renaming `QiskitDevice.probabilities` to `QiskitDevice.probability` fixed that error for me. Cheers!

**Comment by antalszava** [comment]
I see that makes sense! Thank you so much once again for your addition! :blush: 

The tests are failing due to the test suite pulling the newest version (`0.18`) of Qiskit. We are investigating this right now and creating a fitting solution.

**Comment by antalszava** [comment]
Thanks for catching that @josh146!

@rafaelha, could you please modify the `CHANGELOG.md` file such that it includes:
- a one-sentence description of this PR (for example in the `Bugfix` section);
- yourself as a contributor in the list of contributors for the current release (`# Release 0.9.0-dev`).

Thanks! :blush:

**Pull request merged**
